sudo: required
services:
    - docker

before_install:
    - docker build -t sechung/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run sechung/react-test npm test -- --coverage

after_success:
    - docker build -t sechung/multi-client ./client
    - docker build -t sechung/multi-nginx ./nginx
    - docker build -t sechung/multi-server ./server
    - docker build -t sechung/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push sechung/multi-client
    - docker push sechung/multi-nginx
    - docker push sechung/multi-server
    - docker push sechung/multi-worker